---
- name: Add Jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Install Jenkins
  apt:
    name: jenkins={{ jenkins_lts_version }}
    state: present
    update_cache: yes

- name: Start and enable Jenkins
  service: name=jenkins state=started enabled=yes