---
- name: Forwarding IPv4 and letting iptables see bridged traffic
  ansible.builtin.blockinfile: 
    path: /etc/modules-load.d/k8s.conf
    create: true
    block: |
      overlay
      br_netfilter

- name: Forwarding IPv4 and letting iptables see bridged traffic
  community.general.modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - 'overlay'
    - 'br_netfilter'

- name: Forwarding IPv4 and letting iptables see bridged traffic
  ansible.builtin.blockinfile: 
    path: /etc/sysctl.d/k8s.conf
    create: true
    block: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Forwarding IPv4 and letting iptables see bridged traffic
  ansible.builtin.command: sudo sysctl --system

- name: Install containerd
  apt:
    name: containerd
    state: present

- name: Create directory /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create file /etc/containerd/config.toml
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: touch
    mode: '0644'

- name: Create default /etc/containerd/config file
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: Configuring the systemd cgroup driver
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    search_string: 'SystemdCgroup = false'
    line: '            SystemdCgroup = true'
    
- name: Restart containerd service
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted

- name: Install packages needed to use the Kubernetes apt repository
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes

- name: Download the public signing key for the Kubernetes package repositories
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Add Kubernetes repository line to sources.list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    state: present
    
- name: Install kubelet, kubeadm and kubectl
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes