---
- name: Setup Kubernetes Worker
  hosts: KubernetesWorker
  become: true
  remote_user: ubuntu
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  roles:
    - kubernetes

  tasks:
    - name: Join Kubernetes cluster
      shell: kubeadm join 172.31.16.12:6443 --token 2f1q4y.cip4f2rkefqsxfvl --discovery-token-ca-cert-hash sha256:a2a25e80c0bc5589f62b1d3090b390bc1a629f5272e64996029cdfac6e4629ab