- name: Get kubeadm join command from Kubernetes First Master
  hosts: KubernetesFirstMaster
  become: true
  gather_facts: false

  tasks:
    - name: Print kubeadm join command
      shell: kubeadm token create --print-join-command
      register: k8s_join_cmd
    
    - name: Register dummy host with variable
      ansible.builtin.add_host:
        name: "DUMMY_HOST"
        k8s_join_cmd_var: "{{ k8s_join_cmd.stdout }}"

- name: Setup Kubernetes Workers
  hosts: KubernetesWorkers
  become: true
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Disable swap on ubuntu
      shell: |
            sudo swapoff -a  
            sudo sed -i '/swap/ s/^/#/' /etc/fstab

  roles:
    - kubernetes

  tasks:
    - name: Join Kubernetes Workers
      shell: "{{ hostvars.DUMMY_HOST.k8s_join_cmd_var }}"
      register: join_command_result
      failed_when: 
        - join_command_result.rc != 0
        - "'/etc/kubernetes/kubelet.conf already exists' not in join_command_result.stderr"