---
- name: Setup Kubernetes Worker
  hosts: KubernetesWorker
  become: true
  remote_user: ubuntu
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  roles:
    - kubernetes

  tasks:
    - name: Join Kubernetes cluster
      shell: kubeadm join 172.31.16.12:6443 --token zg8q37.xc6a3fvk0hyshvi0 --discovery-token-ca-cert-hash sha256:ec76950e8ae95b5b5b9fc4a093900bf8022158d7b064a26974cb7d35ddac3046