---
- name: Setup Kubernetes Worker
  hosts: KubernetesWorker
  become: true
  remote_user: ubuntu
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  roles:
    - kubernetes

  tasks:
    - name: Join Kubernetes cluster
      shell: kubeadm join 172.31.16.12:6443 --token o6tjov.tqxd6kgmnoo9r96t --discovery-token-ca-cert-hash sha256:4a35a7d368097a3e1f6832fe4e49834ce72b08c46e53adada89ad197ce0f1afe