---
- name: Setup Kubernetes Master
  hosts: KubernetesMaster
  become: true
  remote_user: ubuntu
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  roles:
    - nginx
    - kubernetes

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Setup Kubernetes cluster
      block:
        - name: Kubeadm init
          shell: kubeadm init --apiserver-cert-extra-sans=18.235.58.152

        - name: Create .kube directory in /home/ubuntu
          file:
            path: /home/ubuntu/.kube
            state: directory
            owner: ubuntu
            group: ubuntu

        - name: Copy admin.conf to /home/ubuntu/.kube
          copy:
            src: /etc/kubernetes/admin.conf
            remote_src: true
            dest: /home/ubuntu/.kube/config
            owner: ubuntu
            group: ubuntu
      tags: setup-kubernetes

    - name: Install Cilium
      block:  
        - name: Set CLI_ARCH variable
          debug: msg="{{ lookup('ansible.builtin.url', 'https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt') }}"
          register: CILIUM_CLI_VERSION
        
        - name: Download cilium-cli install file
          get_url:
            url: https://github.com/cilium/cilium-cli/releases/download/{{ CILIUM_CLI_VERSION.msg }}/cilium-linux-amd64.tar.gz
            dest: /home/ubuntu
            checksum: sha256:https://github.com/cilium/cilium-cli/releases/download/{{ CILIUM_CLI_VERSION.msg }}/cilium-linux-amd64.tar.gz.sha256sum

        - name: Unarchive cilium-cli file to /usr/local/bin
          unarchive:
            src: /home/ubuntu/cilium-linux-amd64.tar.gz
            remote_src: true
            dest: /usr/local/bin

        - name: Remove cilium-cli file in /home/ubuntu
          file:
            path: /home/ubuntu/cilium-linux-amd64.tar.gz
            state: absent

        - name: Install Cilium
          shell: cilium install --version 1.15.2
          become: true
          become_user: ubuntu
      tags: install-cilium

    - name: Install Nginx ingress controller
      block:
        - name: Clone Nginx ingress controller repository
          git:
            repo: https://github.com/nginxinc/kubernetes-ingress.git
            dest: /tmp/nginx-ingress
            version: v3.5.1

        - name: Create a namespace and a service account
          shell: kubectl apply -f /tmp/nginx-ingress/deployments/common/ns-and-sa.yaml

        - name: Create a cluster role and binding for the service account
          shell: kubectl apply -f /tmp/nginx-ingress/deployments/rbac/rbac.yaml

        - name: Create a ConfigMap to customize NGINX settings
          shell: kubectl apply -f /tmp/nginx-ingress/deployments/common/nginx-config.yaml

        - name: Create an IngressClass resource
          shell: kubectl apply -f /tmp/nginx-ingress/deployments/common/ingress-class.yaml

        - name: Install core custom resource definitions
          shell: kubectl apply -f https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.5.1/deploy/crds.yaml

        - name: Deploy Nginx ingress controller
          shell: kubectl apply -f /tmp/nginx-ingress/deployments/deployment/nginx-ingress.yaml
      become_user: ubuntu
      tags: install-nginx-ingress

    - name: Config Nginx
      block:
        - name: Add site config for goal.poeta.click
          template:
            src: sites-config/goal.conf.j2
            dest: /etc/nginx/sites-enabled/goal.conf
          notify:
            - Restart nginx

        - name: Add site config for tkb.poeta.click
          template:
            src: sites-config/tkb.conf.j2
            dest: /etc/nginx/sites-enabled/tkb.conf
          notify:
            - Restart nginx
      tags: config-nginx