---
- name: Setup Kubernetes Worker
  hosts: KubernetesWorker
  become: true
  remote_user: ubuntu
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  roles:
    - kubernetes

  tasks:
    - name: Join Kubernetes cluster
      block:
      tags:
        - kubernetes-config